### ISSUE TITLE
Does not work for OTRS 6.x

### ISSUE THREAD

**Issue by genaumann** [dennykorsukewitz/OTRS-Inventory#2]
Hello,

this module doesn't work for OTRS 6.x.
Could you fix it for OTRS 6?

Best,
Gino ;)

**Comment by dennykorsukewitz** [comment]
hi @SynPrime 

this package is actually designed for 3 and 4.
And not migrate to 6, yet.

If you want to help me, you could make your changes for 6 as a merger quest.
